MetaDataFormat = "toml"
baseurl = "https://drshishu.com"
copyright = "Copyright (c) 2018, Shi Shu; all rights reserved."
disqusShortname = ""
googleAnalytics = ""
languageCode = "zh-CN"
title = "Shi Shu's Personal Website"
[author]
name = "Shi Shu"
[indexes]
tag = "tags"
topic = "topics"
[params]
about = "Welcome to my personal website !"
bg_scroll = ""
copyright = "2018 Shi Shu"
name = "Shi Shu"
[[params.social]]
icon = "envelope-o"
link = "https://drshishu.com"
medium = "Email"
title = "E-mail"
[[params.social]]
icon = "book"
link = "https://drshishu.com"
medium = "Blog"
title = "Blog"
[[params.social]]
icon = "github"
link = "https://drshishu.com"
medium = "Github"
title = "Github"
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
